### ISSUE TITLE
Everblush for Cava

### ISSUE THREAD

**Issue by vt-d** [Everblush/everblush#7]
[The theme](https://github.com/vt-d/cava)
[Cava](https://github.com/karlstav/cava)

**Comment by samuelnihbos** [comment]
cool! Make sure the readme follows the style like the other readme. I'll make the repo and you can open pr to that repo

**Comment by mngshm** [comment]
@vt-d the preview section comes before Installation section.

**Comment by mngshm** [comment]
also @vt-d dont upload  your gif/video on the cava repo itself. Upload your media to [Everblush/assets](https://github.com/Everblush/assets). Make a dir "cava" and upload the gif to it. After doing that just link your gif to the cava repo.

**Comment by mngshm** [comment]
is the port done ?

**Comment by vt-d** [comment]
@Mangeshrex im unable to PR to the repo. Please create a dummy file, so i can fork it and put up a PR.
